name: Build and publish a Docker image to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build_release:
    name: Build Docker Image and Release to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log into Container Register
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: ghcr.io/vtcs5704-team1/vib/nginx:latest, ghcr.io/vtcs5704-team1/vib/nginx:${{ github.sha }}
