name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Build NGINX container'
        run: |
          docker build . --tag ghcr.io/${{ secrets.GITHUB_USER }}/store:latest
          docer push ghcr.io/${{ secrets.GITHUB_USER }}/store:latest