name: Verify a Docker image
on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build NGINX container'
        run: |
          docker build .
