name: Build a Docker image

  pull_request:
    branches:
      - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build NGINX container'
        run: |
          docker build